from .tlbvfi_node import TLBVFI_VFI_TF32

NODE_CLASS_MAPPINGS = {
    "TLBVFI_VFI_TF32": TLBVFI_VFI_TF32
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "TLBVFI_VFI_TF32": "TLBVFI Frame Interpolation (TF32 Optimized)"
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']